### ISSUE TITLE
Missing information about mandatory constraints

### ISSUE THREAD

**Issue by efralaz** [rvilalta/ietf-te-path-computation#35] opened 2017-12-05 11:10 UTC
PCEP offers the possibility to decide whether a constraint (almost any object actually in PCEP) must be considered by the path computation or may be ignored. 

" P flag (Processing-Rule - 1-bit):  the P flag allows a PCC to specify
      in a PCReq message sent to a PCE whether the object must be taken
      into account by the PCE during path computation or is just
      optional.  When the P flag is set, the object MUST be taken into
      account by the PCE.  Conversely, when the P flag is cleared, the
      object is optional and the PCE is free to ignore it.

   I flag (Ignore - 1 bit):  the I flag is used by a PCE in a PCRep
      message to indicate to a PCC whether or not an optional object was
      processed.  The PCE MAY include the ignored optional object in its
      reply and set the I flag to indicate that the optional object was
      ignored during path computation.  When the I flag is cleared, the
      PCE indicates that the optional object was processed during the
      path computation.  The setting of the I flag for optional objects
      is purely indicative and optional.  The I flag has no meaning in a
      PCRep message when the P flag has been set in the corresponding
      PCReq message."

As shown in the text above (from RFC5440), in case an optional object is not managed by the PCE, it's possible to return this fact in the response. 
The proposal is to include a mechanism like that also in the path computation YANG model, at least inside the generic-path-constraints grouping adding a  boolean leaf to specify whether the constraint is mandatory or not. The additional leaf could be added to path-metrics-bound_config, generic-path-affinities and generic-path-srlgs. 

In addition to that, in order to introduce also the function of the I flag, it's also possible to add another Boolean leaf to specify whether the constraint has been ignored, in case the mandatory leaf is set to false (if a path having a constraint with mandatory leaf true cannot honor or manage the constraint, it should return an error instead). 

This would add a powerful feature to the path computation; in any case, if this proposal is not introduced in the YANG, it's needed to clarify the behavior of the path computation in case a constraint cannot be honored: failure ? the best path satisfying the other constraints if any, and with or without indication of the violation ?  

***Actions***
- [ ] Pending discussion about open issue #31 
- [ ] Needs further discussion with TE Tunnel model authors
- [ ] Check if we need to add the preference attribute to the Path Computation RPC

**Comment by italobusi** [comment] 2018-01-15 12:38
@efralaz : what is the difference between this issue and issue #19?

**Comment by efralaz** [comment] 2018-01-15 12:52
#19 was a question. Since so far nothing happened on this matter, we propose here a solution. In fact it's more detailed and includes management of the optional constraints both in the request and in the response.

**Comment by italobusi** [comment] 2018-01-15 15:51
@efralaz : we understand that this issue should be resolved in the TE Tunnel model:

- path-metrics-bounds_config grouping is defined both in yang-te-types and in yang-te. We think the latter should be removed and the former should be updated as per your proposal

- generic-path-affinities and generic-path-srlgs groupings are defined in yang-te-types, which should be updated as per your proposal

If our understanding is correct, could you please raise this issue to the TE Tunnel model authors?

Sergio and Italo

**Comment by italobusi** [comment] 2018-01-15 15:51
@efralaz : why the flags are not proposed to be added to the common-constraints_config grouping?

Sergio and Italo

**Comment by efralaz** [comment] 2018-01-15 16:07
Because in common-constraints_config metrics, affinities and srlgs are not included. Instead there are parameters like te-topology-id or signaling-type that, rather than constraints, appear as directives, or parameters of the required connection and it's hard to understand the meaning of a flag to mark them as "relaxable" (which is the meaning of "relaxing" the topology where the connection is supposed to happen, or the protocol to be used to signal the connection ?) Instead, the metrics, affinities and srlg are just the, say, "true" constraints which makes sense to manage as relaxable or not, in my view.
Note that all parameters that can be relaxable should have their own flag for this purpose.

**Comment by sergiobelotti** [comment] 2018-01-22 10:49
The issue is on discussion with te-tunnel team . See te-tunnel github
https://github.com/ietf-mpls-yang/te/issues/18

**Comment by sergiobelotti** [comment] 2018-07-10 17:08
need to discuss weather to follow  te-tunnel model procedure described in issue #18 https://github.com/ietf-mpls-yang/te/issues/18 of te-tunnel, or to use another approach which will require path-id issue #52

**Comment by italobusi** [comment] 2018-08-02 09:20
Call on August 2, 2018 (Carlo, Francesco, Italo and Sergio): we would try again to align the TE Tunnel model (and, as a consequence, the Path Computation RPC) with the PCEP capabilities

Current differences between PCEP and TE YANG models:
- multiple weighted metrics (addition of YANG models to PCEP)
- tiebreakers (addition of YANG models to PCEP)
- relaxable path constraints (different approach in YANG models and PCEP)
- synchronization vector (missing in YANG models)
- ingress/egress label set (addition of YANG models to PCEP)

**Action (all) - check the list above on the differences between PCEP and TE YANG models**

**Comment by italobusi** [comment] 2021-07-12 08:35
Francesco/Sergio/Italo: alignment with PCEP capability, could be added in a future revision of TE tunnel and/or Path Computation RPC if the need is identified

**Closed by italobusi** 2021-07-12 08:35 UTC
Labels: needs discussion, support from TE tunnel needed
